######################################################
################# Setup Ceph #########################
######################################################
---

# Quick hack to get ssh keys working with ceph
# - name: SSH Key
#   copy:
#     src: "/root/.ssh/{{ item }}"
#     dest: "/root/.ssh"
#     mode: 0400
#   with_items:
#     - "id_rsa"
#     - "id_rsa.pub"
#   when: inventory_hostname in groups['master-servers']

- import_tasks: 00_preflight.yml

- name: Ceph Deploy Block
  block:
    - import_tasks: 05_files.yml
    - import_tasks: 10_install.yml
    - import_tasks: 15_setup.yml
    - import_tasks: 20_deploy.yml
  any_errors_fatal: true
  when: (kube_check_result is defined and kube_check_result.stdout == "")
    or (ceph_status_result is defined and 'HEALTH_ERR' in ceph_status_result.stdout)
    or (ceph_status_result is defined and 'HEALTH_WARN' in ceph_status_result.stdout)
