---

- name: Make sure users don't try to remove master nodes
  fail:
    msg: "Error: You cannot run remove node on master servers. If you want to reload the entire cluster, add -e "kube_reload=true" to your command."
  when: "{{ groups['master-servers'][0] }} in {{ groups['nodes_to_remove'] }}"

- name: remove-node | Drain node except daemonsets resource
  command: >-
    kubectl drain
      --force
      --ignore-daemonsets
      --grace-period {{ drain_grace_period }}
      --timeout {{ drain_timeout }}
      --delete-local-data {{ item }}
  failed_when: false
  delegate_to: "{{ groups['master-servers'][0] }}"
  ignore_errors: yes
  with_items: "{{ groups['nodes_to_remove'] }}"
