---
- name: Check Worker Node
  include_role:
    name: kubernetes/common
    tasks_from: kube_check
  vars:
    type: "node"
    namespace: ""
    resource_name: "{{ ansible_fqdn }}"
    label: ""

- name: Check to see if Kubernetes directory is empty
  find:
    paths: {{ kube_dir }}
    file_type: directory
    patterns: "*"
  register: kubernetes_directory

- name: Check for existing directories
  fail:
    msg: "It appears you have already run the Kubernetes role once. If you are reloading, verify all the nodes you want removed are under nodes_to_remove in the inventory file."
  when: kubernetes_directory.matched | int != 0
