#######################################################
###################  Kubernetes Repo ###############
#######################################################
---
- name: "Setup Kubernetes repo"
  yum_repository:
    baseurl: "{{ kube_baseurl }}"
    description: "Kubernetes YUM repo"
    gpgcheck: true
    gpgkey: "{{ kube_gpgurl }}"
    name: kubernetes